spring:
  application:
    name: file-storage

  aws:
    s3:
      bucket-name: ${BUCKET_NAME}
      region: ${BUCKET_REGION}
      access-key-id: ${ACCESS_KEY_ID}
      secret-access-key: ${SECRET_ACCESS_KEY}

  #  jwt:
  #    public.key: classpath:keys/public.pem
  #    private.key: classpath:keys/private.pem

  devtools:
    restart:
      enabled: true

  output:
    ansi:
      enabled: always

server:
  port: ${SERVER_PORT:8081}
  error:
    include-stacktrace: on_param

logging:
  level:
    root: INFO
    apps.file.storage: DEBUG
  file:
    name: logs/application.log
