services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}
      - 5005:5005
    environment:
      - SERVER_PORT=${SERVER_PORT:-8080}
      - POSTGRES_HOST=${POSTGRES_HOST:-localhost}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-digital_flavor}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - FILE_STORAGE_URL=${FILE_STORAGE_URL:-http://app-file-storage:8081}
    depends_on:
      database:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
