FROM maven:3.9.9-amazoncorretto-21-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn dependency:go-offline -B && \
    mvn clean package -DskipTests

FROM amazoncorretto:21-alpine3.20-jdk
WORKDIR /app
COPY --from=build /app/target/backend*.jar app.jar

EXPOSE ${SERVER_PORT}
EXPOSE 5005

CMD [ "java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=0.0.0.0:5005", "-jar", "-jar", "app.jar" ]
