FROM maven:3.9.9-amazoncorretto-21-alpine
WORKDIR /app
COPY pom.xml ./
COPY src ./src
RUN mvn dependency:go-offline -B

CMD [ "mvn", "spring-boot:run" , "-Dspring-boot.run.jvmArguments=\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005\"" ]
